Make proon interactive with -i

diff --git a/proon b/proon
--- a/proon
+++ b/proon
@@ -7,20 +7,31 @@ if [ -z "$CHECK_ORIGIN" ]; then
 	exit 1
 fi
 
-git branch | grep -v '\<master\>\|^\*' | \
-	while read -r BRANCH; do
-		ST=$(git branch -d "$BRANCH" 2>&1)
-		if [ $? -eq 0 ]; then
-			echo -n "Pruned \"$BRANCH\"; removing from origin..."
-			RST=$(git push origin ":$BRANCH" 2>&1)
-			if [ $? -eq 0 ]; then
-				echo " Removed."
-			else
-				echo
-				echo "Branch \"$BRANCH\" not removed from origin: $RST"
-			fi
-		else
-			ST=$(echo "$ST" | head -n 1 | sed 's/error: //')
-			echo "Branch \"$BRANCH\" not removed: $ST"
+if [ "$1" = "-i" ]; then
+	INTERACTIVE="yes"
+else
+	INTERACTIVE=""
+fi
+
+for BRANCH in $(git branch --merged master | grep -v '\<master\>\|^\*'); do
+	if [ -n $INTERACTIVE ]; then
+		read -p "$(basename $0): remove branch '$BRANCH'? (y)" RESPONSE
+		if [  "$RESPONSE" != 'y' ] && [ "$RESPONSE" != '' ]; then
+			continue
 		fi
-	done
+	fi
+	ST=$(git branch -d "$BRANCH" 2>&1)
+	if [ $? -eq 0 ]; then
+		echo -n "Pruned \"$BRANCH\"; removing from origin..."
+		RST=$(git push origin ":$BRANCH" 2>&1)
+		if [ $? -eq 0 ]; then
+			echo " Removed."
+		else
+			echo
+			echo "Branch \"$BRANCH\" not removed from origin: $RST"
+		fi
+	else
+		ST=$(echo "$ST" | head -n 1 | sed 's/error: //')
+		echo "Branch \"$BRANCH\" not removed: $ST"
+	fi
+done
